HannaVakulenko/filmoteka-team10

- src/js/pagination.js
> пофіксив імпорт

- src/partials/footer.html
- src/sass/layout/_footer.scss
> Footer update

- src/sass/layout/_header.scss
> add hover and focus

- src/js/spinner.js
- src/partials/loading-process/spinner.html
исправил софтлок из-за спинера
> Фикс софтлока

- src/index.js
- src/js/api-servise.js
- src/js/search.js
- src/partials/header.html
- src/sass/layout/_header.scss
> Жанры и год

- src/js/api-servise.js
- src/js/search.js
- src/partials/footer.html
- src/partials/header.html
Додав пошук по слову, та заглушку для відсутньої картинки
> Додав пошук по слову, та заглушку для відсутньої картинки

- src/js/api-servise.js
- src/js/preloader.js
> add Other in to genres

- src/js/modal-film.js
- src/js/trailer.js
- src/sass/components/_modal-film.scss
поправила кнопку "youtube"
пофиксила проблему с подключением трейлера
> fixed-trailer

- src/js/api-servise.js
Додає page в формулу запроса в функції пошук фильма по ключевому слову
> Додає page в файл api-servise

- src/partials/header.html
Видалив автозаповнення при вводі назви філма в search
> Search fix

- src/images/icons.svg
- src/sass/layout/_header.scss
В хедере
додає ховер, фокус для лого (змінює колір на червоний)
та для лупи (збільшується в розмірі) в хедер.
> Додає ховер, фокус для лого

- src/sass/layout/librarypage/_library-content.scss
- src/sass/utils/_base.scss
1 Змінює width контейнера.
2  В стилях до Library-content змінює форму запису на використання миксинів.
> Змінює базові стилі в адаптиві

- src/js/displaying-movies.js
- src/js/pagination.js
Зробив пагінацію по довжені масиву
> Пагінація по довжені масиву

- src/js/api-servise.js
- src/js/search.js
> видалив слайд

- src/js/firebase/dataBase.js
Виправляє помилку рендеринга на сторінці Library, коли в LocalStorage нема даних
> Виправляє помилку рендеринга

- src/js/firebase/dataBase.js
Зняла коментар з кода (який відповідає за відображення року на картці фільма)
> Виправляє помилку в database

- src/js/firebase/dataBase.js
Виправляє спрацьовування кнопок модального вікна
> Виправляє помилки в database

- src/sass/layout/_header.scss
add animation (плавне пояслення тексту)
> add animation

- src/js/api-servise.js
[Зробив, щоб не зникала пагінація при невдалому запиті]
> Fixed pagination

- src/js/firebase/dataBase.js
Виправляє помилки з приходом з бекенда, т.к. іноді приходить undefined в дата реліз
> Виправляє помилки з дата реліза

- src/js/firebase/dataBase.js
- src/js/modal-film.js
Змінює назву кнопок з
"remove to queue' на "remove from queue"
"remove to watched' на "remove from watched"
> Змінює назви кнопок

- src/js/api-servise.js
- src/js/firebase/dataBase.js
- src/js/scroll-up.js
- src/js/testPag.js
> додав скрол и по 20 карток в лайбрари

- src/js/api-servise.js
- src/js/search.js
На перевірку пагінацію по пошуку
> Add scroll

- src/js/api-servise.js
- src/js/displaying-movies.js
> some fixed
